---
title: "NEWS"
author: "Nandan Patil"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# gpbStat

Install from github 
``` r
install.packages("devtools")
library(devtools)
install_github("nandp1/gpbStat")
```

Install from CRAN
``` r
install.packages("gpbStat")
```
Package website [gpbStat](https://nandp1.github.io/gpbStat/)

## Version `0.4.3`

* New index Stress susceptibility index (SSI) included in function `dti`

## Version `0.4.2`

* Included new index DSI in function `dti`.

## Version `0.4.1`

* New function `dti` for estimating drought tolerance indices.

## Version `0.4.0`

* New function `ltcs` for single plant Line x Tester analysis.

* Modifications in `ltcmt` so as to include names of traits, lines and testers in results.  


## gpbStat version 0.3.3

* New function ```ltcmt``` conducts Line x Tester analysis for multiple traits


## gpbStat version 0.3.3

* Changes in the package dataset. 


## gpbStat version 0.3.2

* dm2 function for analyzing Diallel Method 2 data laid in RCBD and Alpha Lattice Design. 


## gpbStat version 0.3.1

* Estimation of Kings Variance is removed from the function. 

## gpbStat version 0.3.0

* Includes two functions `ltc` and `ltcchk` for Line x Tester analysis. 

* Included Genetic component of variance calculated as per King(1961) . 

* Improved vignettes and examples. 


## gpbStat version 0.2.0

* Merged the LT analysis for RCBD and Alpha lattice into single function.  

* Included Genetic variances, PCV, PCV, ECV, Coefficient of variation and broad sense heritability. 

